const SET_ID_MAP: Record<string, string> = {
    // Scarlet & Violet
    'Scarlet & Violet': 'sv1',
    'Paldea Evolved': 'sv2',
    'Obsidian Flames': 'sv3',
    '151': 'sv3pt5',
    'Paradox Rift': 'sv4',
    'Paldean Fates': 'sv4pt5',
    'Temporal Forces': 'sv5',
    'Twilight Masquerade': 'sv6',
    'Shrouded Fable': 'sv6pt5',
    'Stellar Crown': 'sv7',
    'Surging Sparks': 'sv8',
    'Prismatic Evolutions': 'sv8pt5',
    // Sword & Shield
    'Sword & Shield': 'swsh1',
    'Rebel Clash': 'swsh2',
    'Darkness Ablaze': 'swsh3',
    "Champion's Path": 'swsh35',
    'Vivid Voltage': 'swsh4',
    'Battle Styles': 'swsh5',
    'Chilling Reign': 'swsh6',
    'Evolving Skies': 'swsh7',
    'Celebrations': 'cel25',
    'Fusion Strike': 'swsh8',
    'Brilliant Stars': 'swsh9',
    'Astral Radiance': 'swsh10',
    'Pokémon GO': 'pgo',
    'Lost Origin': 'swsh11',
    'Silver Tempest': 'swsh12',
    'Crown Zenith': 'swsh12pt5',
    // Sun & Moon
    'Sun & Moon': 'sm1',
    'Guardians Rising': 'sm2',
    'Burning Shadows': 'sm3',
    'Shining Legends': 'sm35',
    'Crimson Invasion': 'sm4',
    'Ultra Prism': 'sm5',
    'Forbidden Light': 'sm6',
    'Celestial Storm': 'sm7',
    'Dragon Majesty': 'sm75',
    'Lost Thunder': 'sm8',
    'Team Up': 'sm9',
    'Unbroken Bonds': 'sm10',
    'Unified Minds': 'sm11',
    'Hidden Fates': 'sm115',
    'Cosmic Eclipse': 'sm12',
    // XY
    'XY': 'xy1',
    'Flashfire': 'xy2',
    'Furious Fists': 'xy3',
    'Phantom Forces': 'xy4',
    'Primal Clash': 'xy5',
    'Roaring Skies': 'xy6',
    'Ancient Origins': 'xy7',
    'BREAKthrough': 'xy8',
    'BREAKpoint': 'xy9',
    'Fates Collide': 'xy10',
    'Steam Siege': 'xy11',
    'Evolutions': 'xy12',
    // Black & White
    'Black & White': 'bw1',
    'Emerging Powers': 'bw2',
    'Noble Victories': 'bw3',
    'Next Destinies': 'bw4',
    'Dark Explorers': 'bw5',
    'Dragons Exalted': 'bw6',
    'Boundaries Crossed': 'bw7',
    'Plasma Storm': 'bw8',
    'Plasma Freeze': 'bw9',
    'Plasma Blast': 'bw10',
    'Legendary Treasures': 'bw11',
    // HeartGold SoulSilver
    'HeartGold & SoulSilver': 'hgss1',
    'Unleashed': 'hgss2',
    'Undaunted': 'hgss3',
    'Triumphant': 'hgss4',
    'Call of Legends': 'col1',
    // Diamond & Pearl
    'Diamond & Pearl': 'dp1',
    'Mysterious Treasures': 'dp2',
    'Secret Wonders': 'dp3',
    'Great Encounters': 'dp4',
    'Majestic Dawn': 'dp5',
    'Legends Awakened': 'dp6',
    'Stormfront': 'dp7',
    // EX era
    'Ruby & Sapphire': 'ex1',
    'Sandstorm': 'ex2',
    'Dragon': 'ex3',
    'Team Magma vs Team Aqua': 'ex4',
    'Hidden Legends': 'ex5',
    'FireRed & LeafGreen': 'ex6',
    'Team Rocket Returns': 'ex7',
    'Deoxys': 'ex8',
    'Emerald': 'ex9',
    'Unseen Forces': 'ex10',
    'Delta Species': 'ex11',
    'Legend Maker': 'ex12',
    'Holon Phantoms': 'ex13',
    'Crystal Guardians': 'ex14',
    'Dragon Frontiers': 'ex15',
    'Power Keepers': 'ex16',
    // Base set era
    'Base Set': 'base1',
    'Jungle': 'base2',
    'Fossil': 'base3',
    'Team Rocket': 'base4',
    'Gym Heroes': 'gym1',
    'Gym Challenge': 'gym2',
    'Neo Genesis': 'neo1',
    'Neo Discovery': 'neo2',
    'Neo Revelation': 'neo3',
    'Neo Destiny': 'neo4',
    'Legendary Collection': 'lc',
    'Expedition Base Set': 'ecard1',
    'Aquapolis': 'ecard2',
    'Skyridge': 'ecard3',
};

export function getSetLogoUrl(expansion: string): string | null {
    const setId = SET_ID_MAP[expansion];
    if (!setId) return null;
    return `https://images.pokemontcg.io/${setId}/logo.png`;
}
